version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/splitwise
    depends_on:
      - db
    networks:
      - splitwise_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - splitwise_network

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=splitwise
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - splitwise_network

volumes:
  postgres_data:

networks:
  splitwise_network:
    driver: bridge
